#!/usr/bin/env perl

use Text::Markdown;
use Linux::UserXAttr ':all';

my $file1 = $ARGV[0];
my $charset1 = lgetxattr($file1, 'user.charset') || 'UTF-8';


print "Content-Type: text/html; charset=$charset1\r\n";
print "\r\n";

$/ = undef;
print Text::Markdown::Markdown(<>);
